title: Alina Butt 
description: 
Machine Learning Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/alinabutt/">View My LinkedIn Profile</a> 
  

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
