title: Alina Butt # 
logo: "/images/logo.jpg?raw=true" 
description: > # Machine Learning Engineer, Computer Science Graduate
title: Alina Butt 
logo: "/images/logo.jpg?raw=true" 
description: > 
  email: alinabutt@hotmail.co.uk
  <br><br>
  
